version: '3'
services:
  chat-window-demo:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: 
      context: .
      dockerfile: apps/react-chat-window-demo-no-tailwind/Dockerfile
    ports:
      - '8888:80'
    restart: always
volumes:
  mysql: ~