version: '3'
services:
  chat-window-demo-dev:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: 
      context: .
      dockerfile: apps/react-chat-window-demo-no-tailwind/Dockerfile
    ports:
      - '8888:80'
    restart: always
    profiles:
      - dev
  chat-window-demo-prod:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: 
      context: .
      dockerfile: apps/react-chat-window-demo-no-tailwind/Dockerfile
    ports:
      - '8889:80'
    restart: always
    profiles:
      - prod
volumes:
  mysql: ~