name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci 

      - run: npx nx run react-chat-window:build
      - run: cd dist/libs/react-chat-window
      - run: npm publish --access public
