name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          NPM_PUBLISH_KEY: ${{ vars.NPM_PUBLISH_KEY }}
          NPM_PUBLISH_EMAIL: ${{ vars.NPM_PUBLISH_EMAIL }}
        with:
          fetch-depth: 0
      - run: npm ci 

      - run: npx nx run react-chat-window:build
      - run: echo _auth=$NPM_PUBLISH_KEY >> .npmrc
      - run: echo email=$NPM_PUBLISH_EMAIL >> .npmrc
      - run: echo always-auth=true >> .npmrc
      - run: mv .npmrc dist/libs/react-chat-window
      - run: cd dist/libs/react-chat-window && cat .npmrc
      - run: cd dist/libs/react-chat-window && npm publish --access public
